### ISSUE TITLE
IllegalStateException when analyzing classpath

### ISSUE THREAD

**Issue by colinphill-reify** [brcosta/clj-extras-plugin#14]
I clicked the link to analyze the classpath when the notification prompted me to do so, and it led to this exception:
```
java.lang.IllegalStateException: Attempting to call unbound fn: #'clj-kondo.core/run!
	at clojure.lang.Var$Unbound.throwArity(Var.java:45)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at clojure.lang.Var.invoke(Var.java:384)
	at com.github.brcosta.cljstuffplugin.actions.AnalyzeClasspathAction$analyzeWithBuiltinLinter$1.run$lambda-1(AnalyzeClasspathAction.kt:61)
	at com.github.brcosta.cljstuffplugin.util.ClasspathUtilKt.runWithClojureClassloader(ClasspathUtil.kt:17)
	at com.github.brcosta.cljstuffplugin.util.ClasspathUtilKt.runWithClojureClassloader$default(ClasspathUtil.kt:10)
	at com.github.brcosta.cljstuffplugin.actions.AnalyzeClasspathAction$analyzeWithBuiltinLinter$1.run(AnalyzeClasspathAction.kt:55)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The issue seemed to be transient. It only happened when opening my first project after launch (subsequent projects were okay), and manually rerunning the analysis worked fine.

```
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins:
    name.kropp.intellij.makefile (213.5744.224)
    com.namespace.sort.namespace-sort-plugin (1.7)
    com.intellij.plugins.watcher (213.6461.19)
    String Manipulation (8.25.203.5981.1)
    com.cursiveclojure.cursive (1.12.2-eap2-2021.3)
    com.github.brcosta.cljstuffplugin (0.5.2)
    ru.adelf.idea.dotenv (2021.3.0.213)

Kotlin: 213-1.6.10-release-944-IJ6461.79
```

**Comment by brcosta** [comment]
Put a fix on 0.5.4 (already in marketplace), check it out! :)
