### ISSUE TITLE
Two exceptions when opening a project with 0.7.7, Idea 2023.1, Windows 11

### ISSUE THREAD

**Issue by timgilbert** [brcosta/clj-extras-plugin#43]
I'm running Idea 2023.1.2 on Windows 11, opening a WSL2 project with Cursive `1.12.8-2023.1`. Whenever I open intellij I get two exceptions reported and (as far as I can tell) no kondo stuff happens.

First one:

```
Error trying to annotate file

java.io.IOException: Incorrect function
	at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:100)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1328)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at clj_kondo.impl.cache$sync_cache$fn__4180.invoke(cache.clj:167)
	at clj_kondo.impl.cache$sync_cache.invokeStatic(cache.clj:167)
	at clj_kondo.impl.cache$sync_cache.invoke(cache.clj:165)
	at clj_kondo.core$run_BANG_.invokeStatic(core.clj:208)
	at clj_kondo.core$run_BANG_.invoke(core.clj:55)
	at kondoutil$run_with_in_str.invokeStatic(kondoutil.clj:2)
	at kondoutil$run_with_in_str.invoke(kondoutil.clj:2)
	at clojure.lang.Var.invoke(Var.java:388)
	at com.github.brcosta.cljstuffplugin.extensions.CljKondoAnnotator.lintWithBuiltinLinter(CljKondoAnnotator.kt:108)
	at com.github.brcosta.cljstuffplugin.extensions.CljKondoAnnotator.doAnnotate(CljKondoAnnotator.kt:61)
	at com.github.brcosta.cljstuffplugin.extensions.CljKondoAnnotator.doAnnotate(CljKondoAnnotator.kt:31)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:198)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:274)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:175)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:350)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:340)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:297)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:280)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
	at com.intellij.util.Alarm$Request.run(Alarm.java:354)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Second exception (this seems to be #30):

```
java.lang.RuntimeException: Unsupported escape character: \.
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$StringReader.invoke(EdnReader.java:457)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.lang.EdnReader.readString(EdnReader.java:67)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.java.api.Clojure.read(Clojure.java:93)
	at com.github.brcosta.cljstuffplugin.actions.AnalyzeClasspathAction$analyzeWithBuiltinLinter$1.run(AnalyzeClasspathAction.kt:81)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

IntelliJ details:

```
IntelliJ IDEA 2023.1.2 Preview (Community Edition)
Build #IC-231.9011.4, built on May 4, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Non-Bundled Plugins:
    com.cursiveclojure.cursive (1.12.8-2023.1)
    com.github.brcosta.cljstuffplugin (0.7.7)

Kotlin: 231-1.8.21-IJ9011.4
```

I don't have a full repo to reproduce it, but the lein project that it's trying to open looks like this:

```clojure
(defproject foo "0.1.0-SNAPSHOT"
  :description "foo"
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [cheshire "5.8.1"]
                 [com.taoensso/timbre "6.1.0"]
                 [mvxcvi/puget "1.3.4"]
                 [metosin/malli "0.11.0"]
                 [io.replikativ/datahike "0.6.1540"]]
  :profiles {:uberjar {:aot :all}
             :dev {:plugins [[lein-bin "0.3.4"]]
                   :dependencies [[lambdaisland/kaocha "1.82.1306"]
                                  [com.lambdaisland/kaocha-doctest "0.1.15"]
                                  [kaocha-noyoda "2019-06-03"]]}}
  :aliases {"kaocha" ["run" "-m" "kaocha.runner"]}
  :main foo.main)
```

**Comment by timgilbert** [comment]
As an update, I've tried to use an external clj-kondo instead of the built-in one, but I'm having no dice in a Windows WSL2 environment either. From the Windows PowerShell command-line I can invoke the WSL version via `wsl '/usr/bin/clj-kondo'` but adding that as my "clj-kondo external path" doesn't pass [this check for file existence](https://github.com/brcosta/clj-extras-plugin/blob/main/src/main/kotlin/com/github/brcosta/cljstuffplugin/extensions/CljKondoAnnotator.kt#L60) so it always runs the built-in kondo and getting the errors above.

**Comment by timgilbert** [comment]
I believe #56 should fix this exception.
